name: Sanity checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43

      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Checks
        run: make
